AutoserviceDiplom/Controllers/StoreSparePartsController.cs
using AutoserviceDiplom.Helpers;
using AutoserviceDiplom.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web.Mvc;
namespace AutoserviceDiplom.Controllers
{
     [Authorize]
    public class StoreSparePartsController : Controller
    {
        private autoserviceDEntities db = new autoserviceDEntities();
        //
        // GET: /StoreSpareParts/
        public ActionResult List()
        {
            Employee emptyEmpl=new Employee{ NameSerName="Выбрать сотрудника..."};
            List<Employee> collectionList = db.Employees.Where(f => f.Post.ID_post == "mngparts" && f.ContractToEmployees.FirstOrDefault(d => d.DismissDate == null) != null).ToList();
            collectionList.Add(emptyEmpl);
            ViewBag.ListEmployee = new SelectList(collectionList, "PersonnelNumber", "NameSerName", 0);
            return View();
        }
        public ActionResult Search(SearchPartsOfStoreViewModel model)
        {
            Session["searchParams"] = model;
            ObjectParameter countOfRows = new ObjectParameter("countOfRows", typeof(int));
            List<FindSpareParts_Result> result = db.FindSpareParts(model.ID_part,
                                                                    model.Name,
                                                                    model.Manufacture,
                                                                    model.PriceBefore,
                                                                    model.PriceAfter,
                                                                    model.ID_invoice,
                                                                    model.StockPercent,
                                                                    model.DateIvoiceFrom,
                                                                    model.DateIvoiceBefore,
                                                                    model.PersonnelNumber,
                                                                    "Name", true, 1, 8, countOfRows //для сортировки и пейджинга
                                                                    ).ToList();
            ViewBag.ListEmployee = new SelectList(db.Employees, "PersonnelNumber", "NameSerName");
                return PartialView("ResultSearch", result.ToCustomPageList(1, 8, countOfRows.Value as int?));
            
        }

        [HttpPost]
        public ActionResult SortByParam(int? nmb_clmn, bool? is_accend, int? PageNumber)
        {
            //save sort params in case those variables haven't values 
            if (nmb_clmn.HasValue && is_accend.HasValue)
            {
                Session["nmb_clmn"] = nmb_clmn;  // save at session prop
                Session["is_accend"] = is_accend;
            }
            else
            {
                nmb_clmn = Session["nmb_clmn"] as int?;  // get from session prop if vars is null
                is_accend =Session["is_accend"] as bool?;
            }
            ObjectParameter countOfRows = new ObjectParameter("countOfRows", typeof(int));
            is_accend= is_accend??true;
            string nameSortColumn = String.Empty;
            int pageSize = 8;
            int pageNumber = (PageNumber ?? 1);
            switch (nmb_clmn)
            {
                case 1: nameSortColumn = "Name"; break;
                case 2: nameSortColumn = "ID_part"; break;
                case 3: nameSortColumn = "LotNumber"; break;
                case 4: nameSortColumn = "Manufacture"; break;
                case 5: nameSortColumn = "Unit"; break;
                case 6: nameSortColumn = "Stock"; break;
                case 7: nameSortColumn = "Price"; break;
                case 8: nameSortColumn = "Trade_Increase"; break;
                case 9: nameSortColumn = "Cost"; break;
                case 10: nameSortColumn = "PersonnelNumber"; break;
                case 11: nameSortColumn = "DeliveryDate"; break;
                default: nameSortColumn = "Name"; break;
            }

            var model = Session["searchParams"] as SearchPartsOfStoreViewModel;
            if (model != null)
            {
                List<FindSpareParts_Result> result = db.FindSpareParts(model.ID_part,
                                                                        model.Name,
                                                                        model.Manufacture,
                                                                        model.PriceBefore,
                                                                        model.PriceAfter,
                                                                        model.ID_invoice,
                                                                        model.StockPercent,
                                                                        model.DateIvoiceFrom,
                                                                        model.DateIvoiceBefore,
                                                                        model.PersonnelNumber,
                                                                        nameSortColumn, is_accend, pageNumber, pageSize, countOfRows //для сортировки и пейджинга
                                                                        ).ToList();

                ViewBag.ListEmployee = new SelectList(db.Employees, "PersonnelNumber", "NameSerName");

                return PartialView("ResultSearch", result.ToCustomPageList(pageNumber, pageSize, countOfRows.Value as int?));
            }
            else
                return null;
        }

        [HttpPost]
        public ActionResult ChangeTradeIncrease(int[] ID_position, byte? trd_incr)
        {
            if (ID_position.Length != 0 && trd_incr.HasValue)
            {
                bool isError = false;
                foreach (var item in ID_position)
                {
                    var pos= db.Acceptance_Invoice.Find(item);
                    if (pos != null)
                    {
                        pos.Trade_Increase = trd_incr.Value;
                    }
                    else
                        isError = true;
                }
                if (!isError)
                {
                    try { db.SaveChanges(); return Json(1); }
                    catch (Exception ex) { return Json(-1); }
                }

                else
                    return Json(-1);
            }
            else
                return Json(-1);
        }
	}
}

AutoserviceDiplom/Views/StoreSpareParts/List.cshtml
@model AutoserviceDiplom.Models.SearchPartsOfStoreViewModel
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/store-spare-parts.css" rel="stylesheet"/>
<div class="header-page">Запасные части и материалы на складе</div>
<div class="col-md-12 bs-callout bs-callout-info">

    @using (Ajax.BeginForm("Search", "StoreSpareParts", null, new AjaxOptions { UpdateTargetId = "results", LoadingElementId = "loading", LoadingElementDuration = 100 }, new { @class = "form-horizontal", id = "form-search" }))
{
    <div class="col-md-12 redefined">
        <div class="col-md-2  form-group">
            @Html.EditorFor(m => m.ID_part, new { htmlAttributes = new { @class = "form-control", placeholder = "ID запчасти" } })
        </div>
        <div class="col-md-3  form-group">
            @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Наименование" } })
        </div>
        <div class="col-md-2  form-group">
            @Html.EditorFor(m => m.Manufacture, new { htmlAttributes = new { @class = "form-control", placeholder = "Производитель" } })
        </div>
        <div class="col-md-2  form-group">
            @Html.EditorFor(m => m.StockPercent, new { htmlAttributes = new { @class = "form-control", placeholder = "% остатка" } })
        </div>
        <div class="col-md-2  form-group">
            @Html.EditorFor(m => m.ID_invoice, new { htmlAttributes = new { @class = "form-control", placeholder = "# док. поставки" } })         
        </div>
        <div class="col-md-1 form-group" style="width:15%">
            <button type="submit" class="btn btn-primary" style="width:100%">Найти</button>
        </div>
        <div class="col-md-1 form-group">
            <button type="reset" class="btn btn-default" style="width:100%">Сброс</button>
        </div>
    </div>
    <div class="col-md-12 redefined">
        <div class=" col-md-2 form-group">
            <div class="input-group">
                @Html.EditorFor(m => m.PriceAfter, new { htmlAttributes = new { @class = "form-control", @placeholder = "Цена от" } })
                <span class="input-group-addon">
                    <span>BYN</span>
                </span>
            </div>
        </div>
        <div class=" col-md-2 form-group">
            <div class="input-group">
                @Html.EditorFor(m => m.PriceBefore, new { htmlAttributes = new { @class = "form-control", @placeholder = "до" } })
                <span class="input-group-addon">
                    <span>BYN</span>
                </span>
            </div>
        </div>
        <div class=" col-md-2 form-group">
            <div class="input-group date" id="dtPick_From">
                @Html.EditorFor(m => m.DateIvoiceFrom, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "Поставка с" } })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <div class=" col-md-2 form-group">
            <div class="input-group date" id="dtPick_Before">
                @Html.EditorFor(m => m.DateIvoiceBefore, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "до" } })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <div class="col-md-3  form-group">
            @Html.DropDownListFor(m=>m.PersonnelNumber, ViewBag.ListEmployee as SelectList, new { @class = "form-control"})
        </div>
    </div>
}
    <div id="results" style="margin-top:80px">

    </div>
</div>
<img id="loading" src="@Url.Content("~/Content/Images/loading.gif")" style="display: none; position: absolute; margin: auto; top: 0; bottom: 0; left: 0; right: 0" />
@section Script{
    @Scripts.Render("~/Scripts/moment-with-locales.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker.min.js")
    @Styles.Render("~/Content/bootstrap-datetimepicker.min.css")
    <script src="~/Scripts/forViews/store-spare-parts.js"></script>
}

AutoserviceDiplom/Views/StoreSpareParts/ResultSearch.cshtml
@model  AutoserviceDiplom.Helpers.PageListCustom<AutoserviceDiplom.Models.FindSpareParts_Result>
@using AutoserviceDiplom.Helpers
@using AutoserviceDiplom.MyCustomClasses

@if(Model._Elements.Count()!=0)
    {

<table class="table">
  
    <tr>
        <th width="21%">Наименование запчасти @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="10%">ID_запчасти @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="8%">№ партии @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="8%">Произ-ль @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="7%">Ед.изм. @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="7%">Остаток @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="9%">Стоимость @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="7%">% надб. @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="7%">Цена @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="9%">Принял @Html.Hidden("is_accend")<span style="float:right"></span></th>
        <th width="7%">Дата @Html.Hidden("is_accend")<span style="float:right"></span></th>
    </tr>
    @foreach (var item in Model)
    { 
        <tr>
            @Html.Hidden("ID_position",item.ID_position)
            <td>@Html.ActionLink(item.Name, "Manage", "Acceptance", new { LotNumber = item.LotNumber }, new { title="Перейти к накладной поставки"})</td>
            <td>@item.ID_part</td>
            <td>@item.LotNumber</td>
            <td>@item.Manufacture</td>
            <td>@item.Unit</td>
            <td>@item.Stock</td>
            <td>@item.Price</td>
            <td>@item.Trade_Increase</td>
            <td>@item.Cost</td>
            <td>@((ViewBag.ListEmployee as SelectList).Where(f => f.Value == (item.PersonnelNumber == null ? "0" : item.PersonnelNumber.Value.ToString())).FirstOrDefault().Text.ConvertToShortName())</td>
            <td>@(item.DeliveryDate.HasValue?item.DeliveryDate.Value.GetDateTimeFormats()[4]:"")</td>
        </tr>
    }
</table>
<div id="popErorr" style="height: 50px; margin-top: 10px;background-color: #F2DEDE; border-radius: 10px; font-size: 16px; color: #A94442; display: none; text-align: center; padding-top: 10px"></div>
<div class="col-md-6 redefined">  
@Html.Raw("Стр.  "+(Model.PageInfo.PageCount < Model.PageInfo.PageNumber ? 0 : Model.PageInfo.PageNumber)+" из "+ Model.PageInfo.PageCount)

@Html.PageProcLinksFor(Model.PageInfo, page => "nextUp(" + page + ");")
</div>
 <div id="trade_incr" style="display:none">   
<div class="col-md-3">
    <label style="float:right;margin-top:5px;" for="trd_incr">Установить торговую надбавку: </label>
</div>
    <div class="col-md-3 redefined">
        <div class="input-group">
            <span class="input-group-addon" style="padding:0">
                <button onclick="applyIncrease()" style="width:50px;height:30px;">&#10004;</button>
            </span>
            <input type="number" name="trd_incr" id="trd_incr" value="30" class="form-control">
            <span class="input-group-addon">
                <span>%  от стоимости</span>
            </span>
        </div>

    </div>
</div>
    }
else
{
    <h3>Нет данных по данному критерию...</h3>
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />