AutoserviceDiplom/Controllers/PreRecordController.cs
using AutoserviceDiplom.Models;
using AutoserviceDiplom.MyCustomClasses;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AutoserviceDiplom.Controllers
{
     [Authorize]
    public class PreRecordController : Controller
    {
        autoserviceDEntities db = new autoserviceDEntities();
        IdentityContext idb=new IdentityContext();
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PreRecordRecivedDataViewModel model_recived)
        {
            ApplicationUser user=  idb.Users.Where(i=>i.UserName==User.Identity.Name).FirstOrDefault();
            if (ModelState.IsValid&&user!=null)
            {
                string stringID_serv = string.Join("|", model_recived.Id_serv);
                var inputParams = new Dictionary<string, object> { 
                                                                    { "name_sern", model_recived.NameSerName}, 
                                                                    { "phone", model_recived.Phone_number??(object)DBNull.Value},
                                                                    { "mark_model", model_recived.MarkModelCar },
                                                                    { "issue_year", model_recived.IssueYear??(object)DBNull.Value},
                                                                    { "reg_nubm", model_recived.RegNumberCar??(object)DBNull.Value},
                                                                    { "pers_numb", user.PersonnelNumber},
                                                                    { "charArrayID_services", stringID_serv }
                                                                 };

                var outputParams = new Dictionary<string, object>{
                                                                    {"id_record",SqlDbType.BigInt}
                                                                 };
                ConnectionLayerDB dbConnection = new ConnectionLayerDB("autoserviceDB");
                int stat = dbConnection.ExecutionProcedure("AddPreRecord", inputParams,  outputParams);
                return RedirectToAction("Details", new { id_record = outputParams["id_record"] });
            }
            return View();
        }
        [HttpPost]
        public ActionResult SearchService(string servname, string id_serv)
        {
            List<Service> services;
            services = db.Services.Where(f => f.ServiceName.Contains(servname) && f.ID_service.Contains(id_serv)&&f.Available).Take(8).ToList();
            return PartialView("ServiceSearchPartial", services);
        }

        [HttpPost]
        public async Task<ActionResult> AttachService(string id_serv, long? id_record)
        {
            if (id_record.HasValue && id_serv != null)
            {
                if (db.PreRecordServices.Find(id_record, id_serv) == null)
                {
                   // PreRecordService pre_rec_serv= new PreRecordService{ID_record=id_record.Value, ID_service=id_serv};
                    db.Entry(new PreRecordService{ID_record=id_record.Value, ID_service=id_serv}).State=EntityState.Added;
                    await db.SaveChangesAsync();
                    List<PreRecordService> services = db.PreRecords.AsNoTracking().Where(g => g.ID_record ==id_record).FirstOrDefault().PreRecordServices.ToList();
                   return PartialView("ServicesAttachedPartial", services);
                }
                else
                    return HttpNotFound();  
            }
            else
            return HttpNotFound();      
        }

        [HttpPost]
        public ActionResult DeleteAttachService(string ID_service, long? id_record) 
        {
            if (ID_service != null && id_record.HasValue)
            {
                var preserv=db.PreRecordServices.Find(id_record, ID_service);
                if (preserv!= null&&preserv.DateReserv==null)
                {
                    db.PreRecordServices.Remove(preserv);
                    db.SaveChanges();
                    return null;
                }
                else return JavaScript("$('#popErorr').html('Невозможно удалить услугу, так как она уже  в таблице загрузок мастеров или удалена').slideDown(300).delay(1500).slideUp(300); ");
            }
            return HttpNotFound();
        }

        public ActionResult List()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(SearchPreRecordsViewModel model, int? page)
        {

            long recordIntervalDown, recordIntervalUp;
            if (model.ID_record.HasValue)/// для получения диапазона номеров записей, при Null в запросе
            {
                recordIntervalDown = model.ID_record.Value;
                recordIntervalUp = model.ID_record.Value;
            }
            else
            {
                recordIntervalDown = 0;
                recordIntervalUp = 10000000; 
            }
            var pre_records = (from resp in db.PreRecords.AsNoTracking() where (resp.NameSerName.Contains(model.NameClient) || string.IsNullOrEmpty(resp.NameSerName)) &&
                                                                (resp.RegNumberCar.Contains(model.RegNumber) || string.IsNullOrEmpty(resp.RegNumberCar)) &&
                                                                (resp.MarkModelCar.Contains(model.MarkCar) || string.IsNullOrEmpty(resp.MarkModelCar)) &&
                                                                resp.ID_record>=recordIntervalDown&&resp.ID_record<=recordIntervalUp&&
                                                                resp.DateMakingRecord>=model.DateMakingFrom&&resp.DateMakingRecord<=model.DateMakingBefore&&
                                                                (resp.IsRejection == (model.IsRejection ?? false) || resp.IsRejection == (model.IsRejection ?? true))
                                                        select resp).ToList();
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return PartialView("SearchResultPartial", pre_records.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult DeleteRecord(long? ID_record)
        {
            if(ID_record.HasValue)
            {
                var record = db.PreRecords.Find(ID_record);
                if (record != null)
                {
                    db.PreRecords.Remove(record);
                    db.SaveChanges();
                    if (Request.UrlReferrer.AbsolutePath == "/PreRecord/Details")
                        return JavaScript("window.location.href='/PreRecord/List';");
                    else
                        return JavaScript("window.location.reload();");
                }
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult Details(long? id_record)
        {
            PreRecord preRecord = db.PreRecords.Find(id_record);
            if (preRecord != null)
            {
                return View(preRecord);
            }
            else
                return HttpNotFound();
        }

        public ActionResult CastToOrder(long? id_record)
        {
            var record = db.PreRecords.Find(id_record);
            if (record!=null)
            {
                ViewBag.Id_record = id_record;
                string[] namesClient = record.NameSerName.ConvertToStringNames();// имена раздельно
                string serName, name;
                List<Client> targetClients, unionSetClients;
                ClientComparer clntComparer = new ClientComparer();
                serName= namesClient[0];
                name=namesClient[1];
                targetClients = (from rez in db.Clients where rez.NameSerName.Contains(serName) && rez.NameSerName.Contains(name) select rez).ToList();//содержит ли поле NameSerName имя и фамилию
                if (targetClients.Count == 0)// если нет, то проверяем по 3 м буквам фамилии 
                {
                    string subStringName;
                    int sizePart = serName.Length/3;

                    if (serName.Length >= 3)//если фамилия не менее 3 символов
                    {
                        if (sizePart < 3)
                            sizePart = 3;
                        subStringName = serName.Substring(0, sizePart);
                        unionSetClients = (from rez in db.Clients where rez.NameSerName.Contains(subStringName) select rez).ToList();
                        for (int n = sizePart; n < serName.Length - sizePart; n += sizePart) //разделяем фамилию на три части и ищем вхождения по каждой части объединяя наборы данных в один
                        {
                            subStringName = serName.Substring(n, sizePart);
                            unionSetClients = unionSetClients.Union((from rez in db.Clients where rez.NameSerName.Contains(subStringName) select rez).ToList(), clntComparer).ToList();
                        }
                    }
                    else
                    {
                        subStringName = serName;
                        unionSetClients = (from rez in db.Clients where rez.NameSerName.Contains(subStringName) select rez).ToList();
                    }
                    if (unionSetClients.Count >= 1)// если нашли по части фамилии, то показываем пользователю варианты для выбора
                        return PartialView("ListClients", unionSetClients.Take(6));
                    else

AutoserviceDiplom/Views/PreRecord/Create.cshtml
@model AutoserviceDiplom.Models.PreRecordRecivedDataViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/pre-record-create.css" rel="stylesheet" />
<div class="header-page">Регистрация предварительной заявки клиента</div>
<div class="col-md-12 bs-callout bs-callout-info">
    
    @using (Html.BeginForm("Create", "PreRecord", FormMethod.Post, new { id = "form_record" }))
    {
        @Html.ValidationSummary()
        @Html.AntiForgeryToken()
    <div class="col-md-6 redefined form-horizontal">
            <h4>Информация о заказчике</h4>
    <div class="form-group">
        @Html.LabelFor(model => model.NameSerName, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.NameSerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.NameSerName)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Phone_number, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.Phone_number, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
</div>
    <div class="col-md-6 redefined form-horizontal">
        <h4>Информация об автомобиле</h4>
    <div class="form-group">
        @Html.LabelFor(model => model.MarkModelCar, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.MarkModelCar, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(m => m.MarkModelCar)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.IssueYear, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.IssueYear, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RegNumberCar, new { @class = "control-label col-md-3" })
        <div class="col-md-9">
            @Html.EditorFor(model => model.RegNumberCar, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
</div>
    <div class="col-md-6 redefined form-horizontal">
        <h4>Требуемые услуги (работы)</h4>
        <table class="tbl-service-search">
            <tr>
                <th width="50%">Наименование услуги</th>
                <th width="20%">Код работы (ID)</th>
                <th width="15%">Время</th>
            </tr>
        </table>
        <div id="wrap_tbl">
            <table class="tbl-service-search" id="required"></table>
            @Html.ValidationMessageFor(m => m.Id_serv)
        </div>

    </div>
    }
    <div class="col-md-6 redefined form-horizontal">
        <h4>
            Добавить услуги (работы)</h4>
    <div>
        @using (Ajax.BeginForm("SearchService", "PreRecord", new AjaxOptions { UpdateTargetId = "contents", HttpMethod = "Post" }, new { @class = "col-md-12 form-inline", id = "form_search", style = "margin-bottom:5px" }))
        {
            <input type="text" name="id_serv" placeholder="ID услуги" style="width:41%" class="form-control">
            <input type="text" name="servname" placeholder="Наименование услуги" style="width:50%" class="form-control">
            <button class="btn btn-default" type="submit">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        }
    </div>
    <div id="contents">

    </div>
</div>

    <div class="col-md-12 redefined">
        <div class="col-md-3 redefined">
            <input value="Отмена" class="btn btn-default" onclick="window.history.back()" type="button">
        </div>
        <div class="col-md-3 redefined">
            <input value="Добавить" class="btn btn-success" type="button" onclick="$('#form_record').submit();">
        </div>
    </div>
    
</div>

<script>
    $(document).ready(function () {
        //прикрепить услугу
        $('#contents').on('click', '.glyphicon-plus', function () {
            var flag = null;
           
            var id_serv = $(this).parent().parent().children().eq(1).html();
            $('#required tr').each(function () {
                var id_s = $(this).children().eq(1).find('input').val();
                if (id_serv == id_s)
                    flag=true;
            });

            if (flag)// если уже есть в таблице, то не добавляем
                return null;   
            var name_serv = $(this).parent().parent().children().eq(0).html();
            var time_serv = $(this).parent().parent().children().eq(2).html();
            var target_row = '<tr><td width="60%">' + name_serv + '</td><td width="25%">' + id_serv + '<input type="hidden" name="id_serv" value="' + id_serv + '"/></td><td width="10%">' + time_serv + '</td><td width="5%"><i class="glyphicon glyphicon-remove"></i></td></tr>'
            $('#required').append(target_row);
        })
        // открепить услугу
        $('#required').on('click', '.glyphicon-remove', function () {
            $(this).parent().parent().remove();
        })
    })
</script>

AutoserviceDiplom/Views/PreRecord/Details.cshtml
@model AutoserviceDiplom.Models.PreRecord
@using AutoserviceDiplom.MyCustomClasses
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/pre-record-detalis.css" rel="stylesheet" />
<div class="header-page">Информация о предварительной записи</div>
<div class="col-md-12 bs-callout bs-callout-info">
    
        <div class="col-md-6 redefined">
            <div class="custom-form-group group-green">
                @Html.LabelFor(model => model.NameSerName)
                <span> @Html.DisplayFor(model => model.NameSerName)</span>
            </div>
            <div class="custom-form-group group-green">
                @Html.LabelFor(model => model.Phone_number)
                <span> @Html.DisplayFor(model => model.Phone_number)</span>
            </div>
        </div>
        <div class="col-md-6 redefined">
            <div class="custom-form-group group-sand">
                @Html.LabelFor(model => model.MarkModelCar)
                <span> @Html.DisplayFor(model => model.MarkModelCar)</span>
            </div>
            <div class="custom-form-group group-sand">
                @Html.LabelFor(model => model.IssueYear)
                <span> @Html.DisplayFor(model => model.IssueYear)</span>
            </div>
            <div class="custom-form-group group-sand">
                @Html.LabelFor(model => model.RegNumberCar)
                <span> @Html.DisplayFor(model => model.RegNumberCar)</span>
            </div>
        </div>
    <div class="col-md-12 redefined">
        <div class="custom-form-horizontal">
            <div class="custom-form-group group-light-grey">
                @Html.LabelFor(model => model.Employee.NameSerName)
                <span> @Html.DisplayFor(model => model.Employee.NameSerName)</span>
            </div>
            <div class="custom-form-group group-light-grey">
                @Html.LabelFor(model => model.DateMakingRecord)
                <span> @Html.DisplayFor(model => model.DateMakingRecord)</span>
            </div>
            <div class="custom-form-group group-light-grey">
                @Html.LabelFor(model => model.IsRejection)
                <span>@(!Model.IsRejection.Value? "активна" : "отказ/просрочено")</span>
            </div>
        </div>
    </div>
        <div class="col-md-12 redefined">
            <h4 style="text-align:center">Список планируемых услуг</h4>
            <div id="wrap_tbl">  
                <table class="tbl-service-search" id="required">
                    
                    <tr>
                        <th width="45%">Наименование услуги</th>
                        <th width="20%">Код работы (ID)</th>
                        <th width="5%">Время</th>
                        <th width="10%">Дата старта</th>
                        <th width="10%">Исполнитель</th>
                    </tr>
                    @foreach (var item in Model.PreRecordServices.OrderByDescending(o=>o.DateReserv))
                    {
                        <tr>
                            <td>@item.Service.ServiceName</td>
                            <td>@item.ID_service</td>
                            <td>@item.Service.RateTime</td>
                            <td>@item.DateReserv</td>
                            <td>@(item.Employee==null?"":item.Employee.NameSerName.ConvertToShortName())</td>
                        </tr>
                    }
                    @if(Model.PreRecordServices.Count>0)
                    { 
                    <tr>
                        <th style="text-align:right" colspan="2">Суммарно время работ по нормам</th>
                        <th>@(Model.PreRecordServices.Select(m => m.Service.RateTime).Aggregate((f, e) => f + e))</th>
                        <th>X</th>
                        <th>X</th>
                    </tr>
                    }
                </table>
            </div>
        </div>
        <div class="col-md-12 redefined">
            <div class="col-md-1 redefined">
                <input value="К поиску" class="btn btn-default" onclick="window.location.href='@Url.Action("List", "PreRecord")'" type="button">
            </div>
            @if (!Model.IsRejection.Value)
            {
            <div class="col-md-3 redefined">
                <input value="Распределить работы (услуги) по мастерам" class="btn btn-success" type="button" onclick="javascript:window.location.href='@Url.Action("TableLoadPreReserv", "WorkLoading", new { id_pre_record = Model.ID_record })'">
            </div>
            <div class="col-md-2 redefined">
                <input value="Зарегистрировать как заказ" class="btn btn-success" type="button" onclick="CastRecord('@Model.ID_record')">
            </div>
            }
            <div class="col-md-2 redefined" style="float:right">
                <input value="@(Model.IsRejection.Value?"Восстановить заявку":"Отменить заявку")" class="btn btn-warning" type="button" onclick="javascript:window.location.href='@Url.Action("ChangeStatlRecord", "PreRecord", new { id_pre_record = Model.ID_record })'">
            </div>
            <div class="col-md-2 redefined" style="float:right">
                <input value="Удалить заявку" class="btn btn-danger" type="button" onclick="confirmDialog('Вы уверены,  что хотите удалить предварительную запись № @Model.ID_record клиента @Model.NameSerName?', DeleteRecord, '@Model.ID_record');">
            </div>
        </div>

    </div>


<script src="~/Scripts/forViews/pre-record-details.js"></script>
@*модальное окно*@
<div class="DialogComfirms">
    <div id="contents" class="col-md-10">
    </div>
    <i class="glyphicon glyphicon-question-sign sing-question"></i>
    <hr>
    <div class="col-md-12 form-inline">
        <button id="ok" class="btn btn-danger">Ок</button>
        <button id="cancel" class="btn btn-success">Отмена</button>
    </div>
</div>
<div id="overlay"></div>

<div id="modal_form">
    <!-- Сaмo oкнo -->
    <span class="glyphicon glyphicon-remove" id="modal_close"></span> <!-- Кнoпкa зaкрыть -->
    <div id="contents2">

    </div>
    <img id="loading" src="@Url.Content("/Content/Images/loading.gif")" style="display: none; position: absolute; margin: auto; top: 0; bottom: 0; left: 0; right: 0" />
</div>
<div id="overlay2"></div><!-- Пoдлoжкa -->

AutoserviceDiplom/Views/PreRecord/List.cshtml
@model AutoserviceDiplom.Models.SearchPreRecordsViewModel
@using AutoserviceDiplom.MyCustomClasses
@{
    ViewBag.Title = "DisplayOrdersByClient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/pre-record-list.css" rel="stylesheet" />
<div class="header-page">Поиск предварительных заявок клиентов</div>
<div class="col-md-12 bs-callout bs-callout-info"> 
    @using (Ajax.BeginForm("Search", "PreRecord", null, new AjaxOptions { UpdateTargetId = "results", LoadingElementId = "loading", LoadingElementDuration = 0 }, new { @class = "col-md-12 redefined form-horizontal", id = "form-search" }))
{
        <div class="col-md-1  form-group">
            @Html.EditorFor(m => m.ID_record, new { htmlAttributes = new { @class = "form-control", placeholder = "№ записи" } })
        </div>
        <div class="col-md-2  form-group">
            @Html.EditorFor(m => m.NameClient, new { htmlAttributes = new { @class = "form-control", placeholder = "ФИО клиента" } })
        </div>
        <div class="col-md-2  form-group">
            @Html.EditorFor(m => m.MarkCar, new { htmlAttributes = new { @class = "form-control", placeholder = "Модель/марка авто" } })
        </div>
        <div class="col-md-2  form-group">
            @Html.EditorFor(m => m.RegNumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Рег.номер авто" } })
        </div>
        <div class="col-md-2" style="width:12%">
            
            <label>
                <input class="checkbox" type="checkbox" name="IsRejection" value="">
                <span class="checkbox-custom"></span>
                <span class="label">Просрочен<br>или отказ</span>
            </label>
        </div>
    <div class=" col-md-2" style="width:15%">
        <div class="input-group date" id="dtPick_From">
            @Html.EditorFor(m => m.DateMakingFrom, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "От" } })
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
            </span>
        </div>
    </div>
        <div class=" col-md-2">
            <div class="input-group date" id="dtPick_Before">
                @Html.EditorFor(m => m.DateMakingBefore, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @placeholder = "До" } })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        <div class="col-md-1 redefined">
            <button type="submit" class="btn btn-primary" style="width:100%">Найти</button>
        </div>
}
    <div id="results" style="margin-top:80px"></div>
</div>
<img id="loading" src="@Url.Content("~/Content/Images/loading.gif")" style="display: none; position: absolute; margin: auto; top: 0; bottom: 0; left: 0; right: 0" />
@section Script{
    @Scripts.Render("~/Scripts/moment-with-locales.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker.min.js")
    @Styles.Render("~/Content/bootstrap-datetimepicker.min.css")
    <script src="~/Scripts/forViews/pre-record-list.js"></script>
}

AutoserviceDiplom/Views/PreRecord/ListClients.cshtml
@model IEnumerable<AutoserviceDiplom.Models.Client>

@(Model.Count()>1?Html.Raw("<h4>Выберите подходящего клиента для перехода к оформлению заказа</h4>"):Html.Raw("<h4>Это требуемый клиент для регистрации заказа?</h4>"))
<ol>
    @foreach(var item in Model)
    {
        <li><a href='@Url.Action("AddOrder", "Order", new { ID = item.ID_client, id_record = ViewBag.Id_record })'>@item.NameSerName</a></li>
        <ul>
            <li>Номер прав: @item.NumberDriveLicense</li>
            <li>Адрес: @item.Adress</li>
        </ul>
    }
</ol>
<a style="text-align:center" href='@Url.Action("CreateNewClient", "Client", new { id_record = ViewBag.Id_record })'>Привязать заявку № @ViewBag.Id_record для нового клиента</a>

AutoserviceDiplom/Views/PreRecord/SearchResultPartial.cshtml
@model PagedList.IPagedList<AutoserviceDiplom.Models.PreRecord>
@using AutoserviceDiplom.MyCustomClasses
@using AutoserviceDiplom.Helpers
<hr>
<ul class="list-group">

    @foreach (var i in Model)
    {

        <li class="list-group-item green" style="height:45px;">
            <div class="col-md-12" style="padding-right:0; padding-left:0px">
                <div onclick="javascript:window.location='@Url.Action("Details", "PreRecord", new { id_record = @i.ID_record })'">
                    <div class="col-md-4 form-group" style="padding:0">
                        <span class="order">Заявка № @i.ID_record  от клиента: @i.NameSerName.ConvertToShortName()</span>
                    </div>
                    <div class="col-md-2 form-group ">
                        <span class="my-lable" style="font-size:12px">от @i.DateMakingRecord</span>
                    </div>

                    <div class="col-md-5 form-group">
                        <span>Статус заявки:</span>
                        <span class='@(i.IsRejection == false ? "my-lable my-lable-ok" : "my-lable my-lable-cancel")' style='font-size:12px'> @(i.IsRejection == false? "запланирован" : "просрочен/отменен")</span>
                    </div>
                </div>
                <div class="col-md-1 form-group">
                    <button class="btn btn-primary" style="padding: 3px 5px 0px 5px; margin-left: 50px" onclick="confirmDialog('Вы уверены,  что хотите удалить предварительную запись № @i.ID_record?', DeleteRecord, '@i.ID_record');">
                        <span class="glyphicon glyphicon-remove-sign"></span>
                    </button>
                </div>
            </div>
        </li>

    }
</ul>
@Html.Hidden("page", Model.PageNumber)
Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
@Html.PageLinksFor(Model, page => "$('#page').attr('value', " + page + ");")
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<script>

    //удаление заказа
    function DeleteRecord(idOrd) {
            $.ajax(
               {
                   url: '@Url.Action("DeleteRecord", "PreRecord")',
                   data: 'ID_record=' + idOrd,
                   type: "GET",
                   datatype: "json",
               })
    }
    $(document).ready(function () {
        $('div[onclick]').click(function () {
            $(this).parent('div[class="col-md-12"]').replaceWith('<div class="progress progress-striped active"><div class="progress-bar" style="width: 100%">Идет загрузка... подождите пожалуйста! </div></div>');
            $('div[onclick]').each(function () {
                $(this).off('click');
                $(this).attr('onclick', '');
            });
        })
    })
</script>
@*модальное окно*@
<div class="DialogComfirms">
    <div id="contents" class="col-md-10">
    </div>
    <i class="glyphicon glyphicon-question-sign sing-question"></i>
    <hr>
    <div class="col-md-12 form-inline">
        <button id="ok" class="btn btn-danger">Ок</button>
        <button id="cancel" class="btn btn-success">Отмена</button>
    </div>
</div>
<div id="overlay"></div>

AutoserviceDiplom/Views/PreRecord/ServiceSearchPartial.cshtml
@model List<AutoserviceDiplom.Models.Service>
<table class="tbl-service-search">
    <tr>
        <th>Наименование услуги</th>
        <th>Код работы (ID)</th>
        <th>Время</th>
        <th></th>
    </tr>
    @foreach (var i in Model)
    {
        <tr>
            <td>@i.ServiceName</td>
            <td>@i.ID_service</td>
            <td>@i.RateTime</td>
            <td><i class="glyphicon glyphicon-plus"></i></td>
        </tr>
    }
</table>

AutoserviceDiplom/Views/PreRecord/ServicesAttachedPartial.cshtml
@model List<AutoserviceDiplom.Models.PreRecordService>
@using AutoserviceDiplom.MyCustomClasses
@foreach (var i in Model.OrderByDescending(f => f.DateReserv))
{
    <tr class="@(i.DateReserv != null ? "reserv-row":"")">
        <td>@i.Service.ServiceName</td>
        <td>@i.ID_service @Html.Hidden("ID_service", i.ID_service)</td>
        <td>@i.Service.RateTime</td>
        <td>@(i.DateReserv != null ? i.DateReserv.Value.GetDateTimeFormats()[7] : "")</td>
        <td>@(i.Employee == null ? "" : i.Employee.NameSerName.ConvertToShortName())</td>
        <td>@(i.DateReserv == null ? Html.Raw("<i class='glyphicon glyphicon-remove'></i>") : Html.Raw(""))</td>
    </tr>
}