AutoserviceDiplom/Controllers/ServiceController.cs
using AutoserviceDiplom.Models;
using PagedList;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AutoserviceDiplom.Controllers
{
    [Authorize]
    public class ServiceController : Controller
    {
        private autoserviceDEntities db = new autoserviceDEntities();

        public ActionResult List()
        {
            ServiceType allTypes= new ServiceType{IDtype=0, TypeName="Все категории"};
            List<ServiceType> listtype = db.ServiceTypes.ToList();
            listtype.Add(allTypes);
            SearchParamsService model = new SearchParamsService {ListTypeServices=new SelectList(listtype, "IDtype","TypeName",0)};
            return View(model);
        }

        public ActionResult Search(SearchParamsService parameters, int? page)
        {
            parameters.PriceStart=parameters.PriceStart ?? 0;
            parameters.PriceEnd = parameters.PriceEnd ?? int.MaxValue;
            parameters.ServId = parameters.ServId ?? "";
            parameters.ServName = parameters.ServName ?? "";
            var lowTypeId= parameters.IDTypeServices==0?1:parameters.IDTypeServices;
            var hiTypeId= parameters.IDTypeServices==0?int.MaxValue:parameters.IDTypeServices;
            List<Service> services = db.Services.Where(f => f.ID_service.Contains(parameters.ServId) && (f.IDtype >= lowTypeId&&f.IDtype<=hiTypeId)&&f.ServiceName.Contains(parameters.ServName)&&
                                                            f.PriceHour>=parameters.PriceStart&&f.PriceHour<=parameters.PriceEnd&&
                                                            (f.Available == (parameters.isAvlble??false) || f.Available == (parameters.isAvlble??true))).ToList();
            int pageSize = 12;
            int pageNumber = (page ?? 1);
            return PartialView("SearchResult", services.ToPagedList(pageNumber, pageSize));
        }
        // GET: /Service/Create
        public ActionResult Create()
        {
            ViewBag.ListTypes = new SelectList(db.ServiceTypes, "IDtype", "TypeName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID_service,ServiceName,RateTime,PriceHour,IDtype,Available")] Service service)
        {
            if (ModelState.IsValid&&db.Posts.Find(service.ID_service) == null)
            {
                db.Services.Add(service);
                db.SaveChanges();
                return RedirectToAction("List");
            }

            ViewBag.ListTypes = new SelectList(db.ServiceTypes, "IDtype", "TypeName", service.IDtype);
            return View(service);
        }

        [HttpGet]
        public ActionResult Edit(string ID_service)
        {
            if (ID_service == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = db.Services.Find(ID_service);
            if (service == null)
            {
                return HttpNotFound();
            }
            ViewBag.ListTypes = new SelectList(db.ServiceTypes, "IDtype", "TypeName");
            return View(service);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID_service,ServiceName,RateTime,PriceHour,IDtype,Available")] Service service)
        {
            if (ModelState.IsValid)
            {
                db.Entry(service).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            ViewBag.IDtype = new SelectList(db.ServiceTypes, "IDtype", "TypeName", service.IDtype);
            return View(service);
        }

        [HttpGet, ActionName("Delete")]
        public ActionResult DeleteConfirmed(string ID_service)
        {
            Service service = db.Services.Find(ID_service);
            db.Services.Remove(service);
            db.SaveChanges();
            return RedirectToAction("List");
        }
        [HttpGet]
        public ActionResult Lock(string ID_service)
        {
            Service service = db.Services.Find(ID_service);
            service.Available = false;
            db.Entry(service).State = EntityState.Modified;
            db.SaveChanges();
            return PartialView("TableRow", service);
        }
        [HttpGet]
        public ActionResult UnLock(string ID_service)
        {
            Service service = db.Services.Find(ID_service);
            service.Available = true;
            db.Entry(service).State = EntityState.Modified;
            db.SaveChanges();
            return PartialView("TableRow", service);
        }
        public ActionResult CheckID(string ID_service)
        {
            if (db.Services.Find(ID_service) != null)
            {
                return Json(ID_service);
            }
            return null;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoserviceDiplom/Views/Service/Create.cshtml
@model AutoserviceDiplom.Models.Service

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
.form-horizontal {
padding-left: 50px;
}

.col-md-3 {
width: 20%;
padding-top: 5px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background: #F6F6F6;
height: 34px;
margin-right: 0px;
text-align:left!important;
      	
}
.col-md-9 {
width: 80%;
margin-left: -15px;
}
.col-md-9 input[type="checkbox"] {
margin-left:30px;
}
</style>
<div class="header-page">Новая услуга</div>
<div class="col-md-12 bs-callout bs-callout-info">
    <div id="popErorr" style ="height: 50px; background-color: #F2DEDE;border-radius:10px;font-size:16px; color: #A94442; display: none; text-align:center; padding-top:10px"></div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.ID_service, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.ID_service, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ID_service)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ServiceName, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.ServiceName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ServiceName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RateTime, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.RateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RateTime)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PriceHour, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.PriceHour, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PriceHour)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDtype, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownListFor(model => model.IDtype, ViewBag.ListTypes as SelectList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDtype)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Available, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.CheckBoxFor(model => model.Available, new { @class = "form-control", @style = "width:10px", @checked="checked" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-9">
                    <input type="submit" value="Добавить" class="btn btn-success" />
                    <input type="button" value="Отмена" onclick="javascript:history.back()" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Назад к списку", "List")
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#ID_service").focusout(function () {
            $.ajax(
                {
                    url: '@Url.Action("CheckID", "Service")',
                    data: $("#ID_service").serialize(),
                    type: "POST",
                    datatype: "json",
                    success: function (result) {
                        if (result != '')
                        {
                            $('#popErorr').html('Услуга, с таким ID (' + result + ') уже существует. Измените ID.').fadeIn(1000);
                        }
                        else
                            $('#popErorr').fadeOut(1000);
                    }
                })
        })
    })

</script>
@section Script{
    @Scripts.Render("~/scripts/jquery.validate.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.js")
}

AutoserviceDiplom/Views/Service/Edit.cshtml
@model AutoserviceDiplom.Models.Service

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
.form-horizontal {
padding-left: 50px;
}

.col-md-3 {
width: 20%;
padding-top: 5px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background: #F6F6F6;
height: 34px;
margin-right: 0px;
text-align: left !important;
}
.col-md-9 {
width: 80%;
margin-left: -15px;
}
.col-md-9 input[type="checkbox"] {
margin-left: 30px;
}
h4{
padding-left:35px;
}
</style>
<div class="header-page">Изменить данные услуги</div>
<div class="col-md-12 bs-callout bs-callout-info">
    <h4>Услуга @Model.ServiceName (@Model.ID_service)</h4>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.ID_service)

            <div class="form-group">
                @Html.LabelFor(model => model.ServiceName, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.ServiceName, new { htmlAttributes = new {@class ="form-control" } })
                    @Html.ValidationMessageFor(model => model.ServiceName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RateTime, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.RateTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RateTime)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PriceHour, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.PriceHour, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PriceHour)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDtype, "IDtype", new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownListFor(model => model.IDtype, ViewBag.ListTypes as SelectList, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IDtype)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Available, new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.CheckBoxFor(model => model.Available, new { @class = "form-control", @style = "width:10px" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-9">
                    <input type="submit" value="Сохранить" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Назад к списку", "List")
    </div>
    </div>

AutoserviceDiplom/Views/Service/List.cshtml
@model AutoserviceDiplom.Models.SearchParamsService

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/services-list.css" rel="stylesheet"/>
<div class="header-page">Список предоставляемых услуг</div>
<div class="col-md-12 bs-callout bs-callout-info">
    @using (Ajax.BeginForm("Search", "Service", null, new AjaxOptions
        {
            UpdateTargetId = "results",
            LoadingElementId = "loading",
            HttpMethod = "Get",
            LoadingElementDuration = 0
        }, new { @class = "form-horizontal", id = "form-search" }))
    {
        @Html.Hidden("page")
    <div class="col-md-12" style="padding:0">
        <div class="col-md-2  form-group">
            @Html.EditorFor(f => f.ServId, new { htmlAttributes = new { @class = "form-control", @placeholder = "ID", id = "search2" } })
        </div>
        <div class="col-md-3  form-group">
            @Html.EditorFor(f => f.ServName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Наименование", id = "search1" } })
        </div>
        <div class="col-md-1" style="width:150px;padding-top:7px">
            <label>
                <input class="checkbox" type="checkbox" name="IsAvlble" value="">
                <span class="checkbox-custom"></span>
                <span class="label">Доступность</span>
            </label>
        </div>
        <div class="col-md-2  form-group">
            @Html.EditorFor(f => f.PriceStart, new { htmlAttributes = new { @class = "form-control", @placeholder = "Цена от", id = "search3" } })
        </div>
        <div class="col-md-1  form-group">
            @Html.EditorFor(f => f.PriceEnd, new { htmlAttributes = new { @class = "form-control", @placeholder = "до", id = "search4" } })
        </div>
        <div class="col-md-2">
            @Html.DropDownListFor(f => f.IDTypeServices, Model.ListTypeServices, new { @class = "form-control"} )
        </div>
        <div class="col-md-1">
            <button type="submit" class="btn btn-primary">Найти</button>
        </div>
        
    </div>
    }
    <div id="results"></div>
    <div class="col-md-12" style="padding-left:0;margin-top:5px">
        <button type="button" onclick="javascript:window.location='@Url.Action("Create")'" class="btn btn-success">Добавить услугу</button>
    </div>
</div>
<img id="loading" src="@Url.Content("~/Content/Images/loading.gif")" style="display: none; position: absolute; margin: auto; top: 0; bottom: 0; left: 0; right: 0" />
<script>
    $().ready(function () {
        //for checkbox
        $('.checkbox').prop("indeterminate", true);
        $('.checkbox').change(function () {
            switch ($(this).attr('value'))
            {
                case 'true':
                    $(this).prop('checked', true).attr('value', false).prop("indeterminate", false);
                    $('.checkbox-custom').removeClass('checkbox-custom-checked'); break;
                case 'false': $(this).prop("indeterminate", true).attr('value', '');
                    $('.checkbox-custom').removeClass('checkbox-custom-checked');break;
                case '': $(this).prop('checked', true).attr('value', true).prop("indeterminate", false);
                    $('.checkbox-custom').addClass('checkbox-custom-checked'); break;

            }
        })
    })
    //for lock or unlock
    $('#results').on('click', '.glyphicon-lock, img', function () {
        var actionName = $(this).hasClass('glyphicon-lock') ? 'UnLock' : 'Lock';
        var idServ = $(this).parent().find('input[type="hidden"]').val();
        $.ajax(
            {
                url: '/Service/' + actionName,
                data: 'ID_service=' + idServ,
                type: "GET",
                datatype: "json",
                success: function (result) {
                    $('table tr>td:nth-child(2):contains(' + idServ + ')').parent().html(result);
                }
            })
    })
</script>

AutoserviceDiplom/Views/Service/SearchResult.cshtml
@model PagedList.IPagedList<AutoserviceDiplom.Models.Service>
@using AutoserviceDiplom.Helpers
@using AutoserviceDiplom.MyCustomClasses
<table class="table info-table">
    <tr>
        <th>
            Наименование услуги
        </th>
        <th>
            ID
        </th>
        <th>
            Норма времени, час
        </th>
        <th>
            Цена за час, byn
        </th>
        <th>
            Доступность
        </th>
        <th>
            Категория
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ID_service)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PriceHour)
            </td>
            <td>
                @((item.Available) == true ? "Доступна" : "Не доступна")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceType.TypeName)
            </td>
            <td>
                <i class="glyphicon glyphicon-edit" title="Редактировать" onclick="javascript:window.location='@Url.Action("Edit", "Service", new { ID_service = item.ID_service })'"></i>
                @if (item.ExecutingServices.Count == 0)
                {
                    <i class="glyphicon glyphicon-remove-circle" title="Удалить" onclick="if(confirm('Вы уверены?')) window.location='@Url.Action("Delete", "Service", new { ID_service = item.ID_service })'"></i>
                }
                @if (item.Available)
                {
                    <img src="~/content/images/unlock-icon.png" style="width:20px;margin-top:-15px; cursor:pointer" title="Заблокировать"/>
                }
                else
                {
                    <i class="glyphicon glyphicon-lock" title="Разблокировать"></i>

                }
                @Html.Hidden("ID_service", item.ID_service)
            </td>
        </tr>
    }

</table>
@Html.Hidden("page", Model.PageNumber)
Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
@Html.PageLinksFor(Model, page => "$('#page').attr('value', " + page + "); $('form:first-child').submit();")
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

AutoserviceDiplom/Views/Service/TableRow.cshtml
@model AutoserviceDiplom.Models.Service
    <td>
        @Html.DisplayFor(modelItem => modelItem.ServiceName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.ID_service)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.RateTime)
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.PriceHour)
    </td>
    <td>
        @((Model.Available) == true ? "Доступна" : "Не доступна")
    </td>
    <td>
        @Html.DisplayFor(modelItem => modelItem.ServiceType.TypeName)
    </td>
    <td>
        <i class="glyphicon glyphicon-edit" title="Редактировать" onclick="javascript:window.location='@Url.Action("Edit", "Service", new { ID_service = Model.ID_service })'"></i>
        @if (Model.ExecutingServices.Count == 0)
        {
            <i class="glyphicon glyphicon-remove-circle" title="Удалить" onclick="if(confirm('Вы уверены?')) window.location='@Url.Action("Delete", "Service", new { ID_service = Model.ID_service })'"></i>
        }
        @if (Model.Available)
        {
            <img src="~/content/images/unlock-icon.png" style="width:20px;margin-top:-15px; cursor:pointer" title="Заблокировать" />
        }
        else
        {
            <i class="glyphicon glyphicon-lock" title="Разблокировать"></i>

        }
        @Html.Hidden("ID_service", Model.ID_service)
    </td>