AutoserviceDiplom/Controllers/PaymentController.cs
using AutoserviceDiplom.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace AutoserviceDiplom.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private autoserviceDEntities db = new autoserviceDEntities();

        // GET: /Payment/
        public ActionResult List()
        {
            return View(db.TypeOfPayments.ToList());
        }

        // GET: /Payment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeOfPayment typeofpayment = db.TypeOfPayments.Find(id);
            if (typeofpayment == null)
            {
                return HttpNotFound();
            }
            return View(typeofpayment);
        }

        // GET: /Payment/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID_Payment,PaymentName")] TypeOfPayment typeofpayment)
        {
            if (ModelState.IsValid && db.TypeOfPayments.Find(typeofpayment.ID_Payment) == null)
            {
                db.TypeOfPayments.Add(typeofpayment);
                db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(typeofpayment);
        }

        // GET: /Payment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeOfPayment typeofpayment = db.TypeOfPayments.Find(id);
            if (typeofpayment == null)
            {
                return HttpNotFound();
            }
            return View(typeofpayment);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID_Payment,PaymentName")] TypeOfPayment typeofpayment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typeofpayment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(typeofpayment);
        }


        [HttpGet, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TypeOfPayment payment = db.TypeOfPayments.Find(id);
            if (payment != null && payment.OrderServs.Count == 0)
            {
                db.TypeOfPayments.Remove(payment);
                db.SaveChanges();
                return Json(1, JsonRequestBehavior.AllowGet);
            }
            return Json(0, JsonRequestBehavior.AllowGet);
        }
        public ActionResult CheckID(int ID_payment)
        {
            if (db.TypeOfPayments.Find(ID_payment) != null)
                return Json(ID_payment, JsonRequestBehavior.AllowGet);
            return null;
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoserviceDiplom/Views/Payment/Create.cshtml
@model AutoserviceDiplom.Models.TypeOfPayment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="header-page">Добавить новый тип оплаты</div>
<div class="col-md-12 bs-callout bs-callout-info">
    <div id="popErorr" style="height: 50px; background-color: #F2DEDE;border-radius:10px;font-size:16px; color: #A94442; display: none; text-align:center; padding-top:10px"></div>
    @using (Html.BeginForm("Create", "Payment", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Payment, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Payment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Payment)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PaymentName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaymentName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("К списку типов платежей", "List")
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#ID_Payment").focusout(function () {
            $.ajax(
                {
                    url: '@Url.Action("CheckID", "Payment")',
                    data: $("#ID_Payment").serialize(),
                    type: "POST",
                    datatype: "json",
                    success: function (result) {
                        if (result != '') {
                            $('#popErorr').html('Тип платежа, с таким ID (' + result + ') уже существует. Измените ID.').fadeIn(1000);
                        }
                        else
                            $('#popErorr').fadeOut(1000);
                    }
                })
        })
    })

</script>

AutoserviceDiplom/Views/Payment/Edit.cshtml
@model AutoserviceDiplom.Models.TypeOfPayment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="header-page">Изменить наименование типа платежа</div>
<div class="col-md-12 bs-callout bs-callout-info">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.PaymentName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PaymentName, new { htmlAttributes = new {@class="form-control" } })
                    @Html.ValidationMessageFor(model => model.PaymentName)
                </div>
            </div>

            @Html.HiddenFor(model => model.ID_Payment)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Сохранить" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("К списку типов платежей", "List")
    </div>
</div>

AutoserviceDiplom/Views/Payment/List.cshtml
@model IEnumerable<AutoserviceDiplom.Models.TypeOfPayment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
i {
font-size: 18px;
}

i:hover {
    cursor: pointer;
}

.glyphicon-remove-circle {
color: #F35047;
}

.glyphicon-edit {
color: #55BE43;
}
</style>
<div class="header-page">Типы платежей</div>
<div class="col-md-12 bs-callout bs-callout-info">
    <div id="popErorr" style="height: 50px; background-color: #F2DEDE;border-radius:10px;font-size:16px; color: #A94442; display: none; text-align:center; padding-top:10px"></div>
    <table class="table info-table" style="width:50%">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PaymentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ID_Payment)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ID_Payment)
                </td>
                <td>
                    <i class="glyphicon glyphicon-edit" title="Редактировать" onclick="javascript:window.location='@Url.Action("Edit", "Payment", new { id = item.ID_Payment })'"></i>
                    @if (item.OrderServs.Count == 0)
                    {
                        <i class="glyphicon glyphicon-remove-circle" title="Удалить" onclick="confirmDialog('Вы уверены,  что хотите удалить  @item.PaymentName ?', delet, '@item.ID_Payment');"></i>
                    }
                </td>
            </tr>
        }

    </table>
    <button class="btn btn-success" type="button" onclick="javascript:window.location='@Url.Action("Create", "Payment")'">Новый тип оплаты</button>
</div>
<script>
    //удаление поставщика
    function delet(id) {
        $.ajax(
        {
            url: '@Url.Action("Delete", "Payment")',
            data: 'id='+id,
            type: "GET",
            datatype: "json",
            success: function (result) {
                if (result == 1)
                    $('table tr>td:contains(' + id + ')').parent().remove();
                else {
                    $('#popErorr').html("Ошибка удаления!").slideDown(500).delay(3000).slideUp(500); return 0;
                }
            }
        })
    }
</script>
@*модальное окно*@
<div class="DialogComfirms">
    <div id="contents" class="col-md-10">
    </div>
    <i class="glyphicon glyphicon-question-sign sing-question"></i>
    <hr>
    <div class="col-md-12 form-inline">
        <button id="ok" class="btn btn-danger">Ок</button>
        <button id="cancel" class="btn btn-success">Отмена</button>
    </div>
</div>
<div id="overlay"></div>